micronaut:
  application:
    name: microcoinShop

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: pwd
    schema: public

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'

vertx:
  pg:
    client:
      port: 5432
      host: localhost
      database: postgres
      user: postgres
      password: pwd
      maxSize: 5

netty:
  default:
    allocator:
      max-order: 3
